# Generated by Django 4.0 on 2022-01-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=10)),
                ('emails', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('postdates', models.DateTimeField(auto_now_add=True)),
                ('visitcounts', models.IntegerField()),
                ('titles', models.CharField(max_length=12)),
                ('contents', models.TextField()),
                ('mainfiles', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
