# Generated by Django 4.0 on 2022-01-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='password',
            new_name='passwords',
        ),
    ]
