# Generated by Django 4.0 on 2022-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0002_rename_password_board_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='visitcounts',
            field=models.CharField(default='0', editable=False, max_length=1000),
        ),
    ]
