# Generated by Django 4.0 on 2022-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0003_alter_board_visitcounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='visitcounts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
