# Generated by Django 4.0 on 2022-01-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0005_alter_board_mainfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='mainfiles',
            new_name='mainphoto',
        ),
    ]
